### ISSUE TITLE
Object Unsubscribe issue

### ISSUE THREAD

**Issue by GirishKanchan** [MurhafSousli/ng2-progressbar#28]
error_handler.js:54 EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: object unsubscribed
Error: Error in :0:0 caused by: object unsubscribed
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:1137:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:35470:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:35535:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:70097:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:110165:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:110138:18)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:71024:20)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:76532:42)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:29796:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:29763:26)
    at http://localhost:4200/vendor.bundle.js:29699:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:29699:29)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:29743:22)
    at http://localhost:4200/vendor.bundle.js:29699:58

**Comment by MurhafSousli** [comment]
Please provide information about the version you are using, your usage of the component (where exactly do you add it and how do you start/stop the progress).

I can think this is the same of issue #27, I will assume that you are moving between 2 routes and you got this error. this is because you added the component in a route component.
put the `<ng-progress></ng-progress>` in your root component template. NOT in a child component

**Comment by GirishKanchan** [comment]
exactly!!!  issue solved thank you
